// Initialize Firebase
const firebaseConfig = {
    apiKey: "AIzaSyC0z-J3LlBLL5qhs_z-Hrb1HcZTMSZlfb4",
    authDomain: "note-app-c5f49.firebaseapp.com",
    projectId: "note-app-c5f49",
    storageBucket: "note-app-c5f49.appspot.com",
    messagingSenderId: "74269273543",
    appId: "1:74269273543:web:6dc4d8646c905129f1fde2"
};

// Initialize Firebase
firebase.initializeApp(firebaseConfig);

// Get a reference to the database service
const database = firebase.firestore();

document.getElementById('generateQR').addEventListener('click', function() {
    const note = document.getElementById('note').value;
    const noteRef = database.collection('notes').doc();
    noteRef.set({ content: note });

    const qrcode = new QRCode(document.getElementById('qrcode'), {
        text: noteRef.id,  // Use the unique ID generated by Firestore
        width: 128,
        height: 128,
    });
});

// Function to retrieve note from Firebase
function retrieveNote(noteId) {
    database.collection('notes').doc(noteId).get()
        .then((doc) => {
            if (doc.exists) {
                const noteContent = doc.data().content;
                document.getElementById('note').value = noteContent;
                console.log("Note retrieved successfully:", noteContent);
            } else {
                console.log("No such document!");
            }
        })
        .catch((error) => {
            console.log("Error getting document:", error);
        });
}

// Example of how to use the retrieveNote function
// You would typically call this when a QR code is scanned
// retrieveNote('scannedNoteId');

// For demonstration, let's add a button to simulate scanning a QR code
const scanButton = document.createElement('button');
scanButton.textContent = 'Simulate QR Scan';
scanButton.addEventListener('click', () => {
    const noteId = prompt("Enter the note ID (simulating QR code scan):");
    if (noteId) retrieveNote(noteId);
});
document.body.appendChild(scanButton);